meta_title: "Benchy - Competitive monitoring made easy."
meta_description: "Benchy lets you monitor automatically your competitors' marketing operations."
meta_image: "logo_meta.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@benchy_app" # indispensable pour les Twitter Cards
